### ISSUE TITLE
Missing vagrant plugin installation in README

### ISSUE THREAD

**Issue by JonatanEnes** [UDC-GAC/ServerlessYARN#1]
Following the guide, after executing 'vagrant up', it may be possible that a missing plugin has to be installed if a new and fresh installation of vagrant is being used. This is solved by executing:

    vagrant plugin install vagrant-hostmanager

Maybe this should be explicitly added to the deployment guide in the README, when the plugin requirements are listed.

**Comment by oscar-castellanos** [comment]
README updated with the suggested command
