### ISSUE TITLE
Root password during BDWatchdog installation

### ISSUE THREAD

**Issue by JonatanEnes** [UDC-GAC/ServerlessYARN#2]
At some point the execution of the 'start_all.sh' script, as the 'vagrant' user, gets stuck with the prompt "root@localhost's password:". This happens more specifically during the installation of BDWatchdog.
![Screenshot_2023-04-14_19-36-30](https://user-images.githubusercontent.com/9095324/232118166-d2856699-7fa0-4202-94fc-71cd1a233b4d.png)

**Comment by JonatanEnes** [comment]
The line at fault where the execution stops is most probably 'hadoop-2.9.2/sbin/start-dfs.sh' in BDWatchdog's 'deployment/metrics/install.sh' script, which is called in the 'bdwatchdog_setup.yml' playbook. This is because BDWatchdog is being installed, probably, using the root user, which can not connect via ssh to localhost.
![Screenshot_2023-04-14_20-18-26](https://user-images.githubusercontent.com/9095324/232125465-983e13fe-31a3-4511-8b4f-9c47887e699a.png)

**Comment by JonatanEnes** [comment]
If the SSH keys are then copied from vagrant's .ssh directory to the root's one, and the script is re-executed, it continues after that point.

    sudo cp /home/vagrant/.ssh/id_rsa* /root/.ssh/

**Comment by oscar-castellanos** [comment]
SSH issue should be fixed with commits 76f52f3df64fe0d22512ea54f2a653731525e2a4 and https://github.com/UDC-GAC/BDWatchdog/commit/39456b1abbdbcbe1950de745807249ea931e0e62

**Comment by JonatanEnes** [comment]
Fixed
