### ISSUE TITLE
Vagrant IP for the server may overlap with the DHCP server in VirtualBox

### ISSUE THREAD

**Issue by JonatanEnes** [UDC-GAC/ServerlessYARN#3]
With the current default configuration for the 'server' Virtual Machine, when vagrant is used to deploy, the IP assigned is 192.168.56.100. The problem is that this IP may also be used for the DHCP server for the host-only networks with VirtualBox. If that happens, any service inside the 'server' VM is inaccessible.

I suggest changing that default IP to 192.168.56.200, or 192.168.56.110, basically any IP that may not overlap with the DHCP server.

**Comment by oscar-castellanos** [comment]
Changed default server IP to 192.168.56.200 in commit 3ed71ed
